### ISSUE TITLE
[REFACTOR] 엔티티 수정

### ISSUE THREAD

**Issue by senzoo-oh** [restroomMAP/restroomMap#14]
## TO-DO 

- [ ] keywords 엔티티 수정
- [ ] reviews 엔티티 수정
- [ ] restroom_keywords 엔티티 삭제
- [ ] review_keywords 엔티티 삭제
