### ISSUE TITLE
[FEATURE] 엔티티 추가 

### ISSUE THREAD

**Issue by senzoo-oh** [restroomMAP/restroomMap#2]
## 개발 시작 전 체크 리스트
- [x] 이슈 제목: [FEATURE] 추가할 기능 내용
- [x] 이슈 넘버 확인하기! > 이슈 넘버를 브랜치 넘버로 사용
- [x] Assignees, Labels 붙이기

## 기능 개요 
엔티티 추가

## TO-DO 

- [x] keyword 엔티티
- [x] restroom 엔티티
- [x] restroomKeyword 엔티티
- [x] review 엔티티
- [x] reviewKeyword 엔티티
- [x] user 엔티티
