### ISSUE TITLE
[Feature] 회원가입

### ISSUE THREAD

**Issue by hyeminboo** [restroomMAP/restroomMap#4]
## 개발 시작 전 체크 리스트
- [x] 이슈 제목: [FEATURE] 추가할 기능 내용
- [x] 이슈 넘버 확인하기! > 이슈 넘버를 브랜치 넘버로 사용
- [x] Assignees, Labels 붙이기

## TO-DO 

- [x] User Entity
- [ ] User Repository
- [ ] User Service
- [ ] User Controller
- [ ] 회원가입 jsp
